version: "3"
services:
  postgres:
    container_name: "postgres"
    restart: always
    image: postgres
    env_file:
      - db.env
      - app-settings.env
    volumes:
      - dk-pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432
    networks:
      - dk-db
  dkapi:
    image: doppelkopf-api
    ports:
      - 5003:80
    depends_on:
      - postgres
    networks:
      - dk-db
    env_file:
      - db.env
  client:
    image: doppelkopf-client
    ports:
      - 8080:80
    restart: always
    depends_on:
      - dkapi
    networks:
      - dk-db



volumes:
  dk-pgdata:

networks:
  dk-db:
    driver: bridge
