version: "3"
services:
  postgres:
#    container_name: "postgres"
    restart: always
    image: postgres
    env_file:
      - db.env
      - app-settings.env
    volumes:
      - dk-pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432
  dkapi:
    image: doppelkopf-api
    depends_on:
      - postgres
    ports:
      - 5003:80
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - db.env
  client:
    image: doppelkopf-client
    ports:
      - 8080:80
    restart: always
    depends_on:
      - dkapi



volumes:
  dk-pgdata:

