version: "3"
services:

  
    client:
        build:
          context: ./client
          dockerfile: Dockerfile
        restart: always
        ports: 
          - 8080:80
        networks:
          - aspnetcoreapp-network

    postgres:
      container_name: 'postgres'
      restart: always
      image: postgres
      environment:
        # change this for a "real" app!
        POSTGRES_USER: doppel
        POSTGRES_PASSWORD: doppel_=983737
        POSTGRES_DB: doppelkopf 
      networks:
        - aspnetcoreapp-network

    dkapi:
        build: 
          context: ./api
          dockerfile: Dockerfile
        ports: 
            - 4000:5000
        networks:
        - aspnetcoreapp-network


volumes:
  pgdata:

networks:
  aspnetcoreapp-network:
    driver: bridge