version: "3"
services: 
    nginx:
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - 5000:80

    postgres:
      container_name: 'postgres'
      restart: always
      image: postgres
      environment:
        # change this for a "real" app!
        POSTGRES_USER: doppel
        POSTGRES_PASSWORD: doppel_=983737
        POSTGRES_DB: doppelkopf 
      networks:
        - dk-db

    dncapi:
        build: 
            context: ./api
            dockerfile: Dockerfile
        ports: 
            - 3000:80
        networks: 
            - dk-db

volumes:
  pgdata:

networks:
  dk-db:
    driver: bridge