// <auto-generated />
using System;
using DoppelkopfApi.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoppelkopfApi.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    partial class SqliteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("DoppelkopfApi.Entities.PlayTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdditionalWeddingPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPlayerPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiamondsAceAsMaster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameVariant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCardSet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundCardsGiversPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("SilentForPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StitchCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableIcon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WeddingWithFirstColorCast")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WithNiner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayTables");
                });

            modelBuilder.Entity("DoppelkopfApi.Entities.TablePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnnouncementReParty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnnouncementVersusParty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CancellationOfparty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameVariant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandCards")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDiamondClubsOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NextTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayedCard")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoundWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundsPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShuffleRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("WinnedRounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TablePlayer");
                });

            modelBuilder.Entity("DoppelkopfApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
